export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_PINGS_SUCCESS = 'LOAD_PINGS_SUCCESS';
export const LOAD_SELECTED_PING_SUCCESS = 'LOAD_SELECTED_PING_SUCCESS';
export const LOAD_SELECTED_PING_DETAILS_SUCCESS = 'LOAD_SELECTED_PING_DETAILS_SUCCESS';
export const LOAD_CUSTOMER_DETAILS_SUCCESS = 'LOAD_CUSTOMER_DETAILS_SUCCESS';
export const LOAD_VEHICLE_DETAILS_SUCCESS = 'LOAD_VEHICLE_DETAILS_SUCCESS';
export const LOAD_INVENTORY_DETAILS_SUCCESS = 'LOAD_INVENTORY_DETAILS_SUCCESS';

